# This Ingress resource is used to route traffic to the whoami service.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

spec:
  rules:
  - host: whoami.internal
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name:  whoami
            port:
              number: 80
  tls:
  - secretName: dw-net-ca # <=== Use the name defined in Certificate resource.